{% set name = "rsync" %}
{% set version = "3.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://www.samba.org/ftp/{{ name }}/src/{{ name }}-{{ version }}.tar.gz
    sha256: 7399e9a6708c32d678a72a63219e96f23be0be2336e50fd1348498d07041df90

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - perl *
    - gnuconfig  # [unix]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}  # [osx and arm64]
    - make
  host:
    - libiconv
    - lz4-c
    - openssl
    - popt 1.16
    - xxhash
    - zlib
    - zstd

test:
  commands:
    - rsync --help

about:
  home: https://rsync.samba.org/
  license: GPL-3.0-only
  license_family: GPL
  license_file: COPYING
  summary: Tool for fast incremental file transfer

  description: |
    rsync is an open source utility that provides fast incremental file transfer.
  doc_url: https://rsync.samba.org/documentation.html
  dev_url: https://git.samba.org/?p=rsync.git

extra:
  recipe-maintainers:
    - notestaff
    - sodre
    - xhochy
