c_compiler:
- gcc
c_compiler_version:
- '12'
cdt_name:
- cos7
cdt_arch:
- armv7l
channel_sources:
- conda-forge
channel_targets:
- conda-forge main
docker_image:
- quay.io/condaforge/linux-anvil-cos7-x86_64
libiconv:
- '1'
lz4_c:
- 1.9.4
openssl:
- '3'
target_platform:
- linux-armv7l
zlib:
- '1.2'
zstd:
- '1.5'
